DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders_products CASCADE;

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(20) NOT NULL,
    customer_surname VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(30) NOT NULL,
    price BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_status VARCHAR(20) NOT NULL,
    customer_id BIGINT REFERENCES customers (customer_id)
);

CREATE TABLE IF NOT EXISTS orders_products(
    order_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders (order_id),
    product_id BIGINT REFERENCES products (product_id)
);


INSERT INTO customers (customer_name, customer_surname)
VALUES ('Иван', 'Иванов'),
       ('Константин', 'Константинов'),
       ('Филипп', 'Филиппов'),
       ('Кирилл', 'Кириллов'),
       ('Алексей', 'Алексеев');

INSERT INTO products (product_name, price)
VALUES ('Молоко', 2),
       ('Хлеб', 3),
       ('Яблоки', 5),
       ('Чай', 10),
       ('Кофе', 15),
       ('Говядина', 20),
       ('Форель', 30);

INSERT INTO orders (order_status, customer_id)
VALUES ('Исполнен', 1),
       ('Исполнен', 2),
       ('Исполнен', 3),
       ('Исполнен', 4),
       ('В процессе доставки', 2),
       ('В процессе доставки', 3),
       ('Комплектуется', 1),
       ('Комплектуется', 5);

INSERT INTO orders_products (order_id, product_id)
VALUES (1, 3),
       (1, 5),
       (1, 7),
       (2, 2),
       (2, 1),
       (2, 4),
       (3, 5),
       (3, 7),
       (4, 4),
       (4, 3),
       (4, 1),
       (5, 6),
       (5, 7),
       (5, 1),
       (6, 2),
       (6, 3),
       (6, 5),
       (7, 6),
       (7, 1),
       (8, 3),
       (8, 4);